apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudl-client
    spec:
      volumes:
      - name: opa-config-vol
        configMap:
          name: opa-istio-config
      containers:
        - name: app
          image: openpolicyagent/demo-restful-api:0.2
          ports:
            - containerPort: 5000
          env:
          - name: POLICY_PATH
            value:  /v1/data/application/main
        - name: opa
          image: openpolicyagent/opa:0.42.2-envoy-rootless
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: opa-config-vol
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5      # Tune these periods for your environemnt
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true  # Include bundle activation in readiness
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
          args:
          - "run"
          - "--server"
          - "--ignore=.*"
          - "--config-file=/config/conf.yaml"
          - "--authorization=basic"
          - "--addr=http://127.0.0.1:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
      containers:
        - name: cloudl-client
          image: kavinduchamiran/cloudl-client:latest
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: CLOUDL_SERVER
              value: cloudl-server-service
  selector:
    matchLabels:
      app: cloudl-client

